export const EXTERNAL_ASSETS = [
  { key: "special_golden_can", path: "assets/sprites/organized-can.png" },
  { key: "special_label_pet", path: "assets/sprites/organized-plastic.png" },
  { key: "special_bundled_paper", path: "assets/sprites/organized-newspaper.png" },
  { key: "special_clean_bottle", path: "assets/sprites/washed-bottle.png" },
  { key: "broom_item", path: "assets/sprites/broom.png", fallback: "createBroomTexture" },
  { key: "flower", path: "assets/sprites/flower.png", fallback: "createFlowerTexture" },
  { key: "recycle_bin_normal", path: "assets/recycling/normal.png" },
  { key: "recycle_bin_can", path: "assets/recycling/can.png" },
  { key: "recycle_bin_plastic", path: "assets/recycling/plastic.png" },
  { key: "recycling_center", path: "assets/recycling/recycling-center.png" },
  { key: "recycling_center_sign", path: "assets/recycling/recycling-center.png" },
  { key: "recycle_vending_machine", path: "assets/vending/vending-machine.png" },
  { key: "jjook_face", path: "assets/portraits/jjook-default.png" },
  { key: "jjook_default", path: "assets/portraits/jjook-default.png" },
  { key: "jjook_lost", path: "assets/portraits/jjook-wallet-lost.png" },
  { key: "jjook_found", path: "assets/portraits/jjook-wallet-found.png" },
  { key: "jjook_smile", path: "assets/portraits/jjook-smile.png" },
  { key: "jjook_expectant", path: "assets/portraits/jjook-expectant.png" },
  { key: "jjook_playful", path: "assets/portraits/jjook-playful.png" },
  { key: "jjook_plogging", path: "assets/portraits/jjook-plogging.png" },
  { key: "jjook_travel_bag", path: "assets/portraits/jjook-travel-bag.png" },
  { key: "haenaem", path: "assets/portraits/haenaem-default.png" },
  { key: "haenaem_confused", path: "assets/portraits/haenaem-confused.png" },
  { key: "haenaem_touched", path: "assets/portraits/haenaem-touched.png" },
  { key: "haenaem_determined", path: "assets/portraits/haenaem-determined.png" },
  { key: "haenaem_surprised", path: "assets/portraits/haenaem-surprised.png" },
  { key: "haenaem_phone", path: "assets/portraits/haenaem-phone.png" },
  { key: "haenaem_sleepy_phone", path: "assets/portraits/haenaem-sleepy-phone.png" },
  { key: "haenaem_sweat", path: "assets/portraits/haenaem-sweat.png" },
  { key: "haenaem_dazed", path: "assets/portraits/haenaem-dazed.png" },
  { key: "haenaem_travel_bag", path: "assets/portraits/haenaem-travel-bag.png" },
  { key: "mother_calm", path: "assets/portraits/mother-calm.png" },
  { key: "mother_smile", path: "assets/portraits/mother-smile.png" },
  { key: "mother_worried", path: "assets/portraits/mother-worried.png" },
  { key: "mother_allowance", path: "assets/portraits/mother-allowance.png" },
  { key: "mother_allowance_2", path: "assets/portraits/mother-allowance-2.png" },
  { key: "yeobi", path: "assets/portraits/yeobi-default.png" },
  { key: "prologue_room_messy", path: "assets/backgrounds/prologue-room-messy.png" },
  { key: "prologue_room_window", path: "assets/backgrounds/prologue-room-window.png" },
  { key: "prologue_desk", path: "assets/backgrounds/prologue-desk.png" },
  { key: "prologue_travel", path: "assets/backgrounds/prologue-travel.png" },
  { key: "prologue_entrance", path: "assets/backgrounds/prologue-entrance.png" },
  { key: "start_park_background", path: "assets/backgrounds/start-park.png" },
  { key: "start_title_1", path: "assets/ui/start-title-1.png" },
  { key: "start_title_2", path: "assets/ui/start-title-2.png" },
  { key: "button_start_game", path: "assets/ui/button-start-game.png" },
  { key: "button_continue", path: "assets/ui/button-continue.png" },
  { key: "button_sound_off", path: "assets/ui/button-sound-off.png" },
  { key: "button_sound_on", path: "assets/ui/button-sound-on.png" },
  { key: "button_settings", path: "assets/ui/button-settings.png" },
  { key: "coffee_cup", path: "assets/ui/coffee-cup.png" },
  { key: "vending_machine_full", path: "assets/vending/vending-machine-full.png" },
  { key: "vending_menu", path: "assets/vending/menu.png" },
  { key: "wallet_item", path: "assets/items/wallet.png" },
  { key: "mother_phone", path: "assets/packing/phone.png" },
  { key: "drink_cola", path: "assets/items/cola.png" },
  { key: "drink_cider", path: "assets/items/cider.png" },
  { key: "drink_water", path: "assets/items/water.png" },
  { key: "bill_1000", path: "assets/items/1000won.png" },
  { key: "speed_buff_icon", path: "assets/effects/acceleration.png" },
  { key: "hospital_building", path: "assets/buildings/hospital-building.png" },
  { key: "pharmacy_building", path: "assets/buildings/pharmacy-building.png" },
  { key: "clothing_store", path: "assets/buildings/clothing-store.png" },
  { key: "convenience_store", path: "assets/buildings/convenience-store.png" },
  { key: "hospital_interior", path: "assets/interiors/hospital-interior.png" },
  { key: "pharmacy_interior", path: "assets/interiors/pharmacy-interior.png" },
  { key: "clothing_store_interior", path: "assets/interiors/clothing-store-interior.png" },
  { key: "pedestrian_light_back", path: "assets/traffic/pedestrian-light-back.png" },
  { key: "pedestrian_stop_sign", path: "assets/traffic/pedestrian-stop-sign.png" },
  { key: "crosswalk_sign", path: "assets/traffic/crosswalk-sign.png" },
  { key: "hospital_doctor", path: "assets/portraits/hospital-doctor.png" },
  { key: "hospital_staff", path: "assets/portraits/hospital-staff.png" },
  { key: "chemist", path: "assets/portraits/pharmacist.png" },
  { key: "clothing_shop_owner", path: "assets/portraits/clothing-shop-owner.png" },
  { key: "sunisuni_portrait_sick", path: "assets/portraits/sunisuni-sick.png" },
  { key: "sunisuni_portrait_smile", path: "assets/portraits/sunisuni-smile.png" },
  { key: "sunisuni_portrait_worried", path: "assets/portraits/sunisuni-worried.png" },
  { key: "sunisuni_bench", path: "assets/props/sunisuni-bench.png" },
  { key: "sunisuni_tree", path: "assets/props/sunisuni-tree.png" },
  { key: "bus_stop_sign", path: "assets/props/bus-stop-sign.png" },
  { key: "street_lamp", path: "assets/props/street-lamp.png" },
  { key: "prescription_item", path: "assets/items/prescription.png" },
  { key: "medicine_bag", path: "assets/items/medicine-bag.png" },
  { key: "bill_5000", path: "assets/items/bill-5000.png" },
  { key: "bill_10000", path: "assets/ui/10000won.png" },
  { key: "travel_bag", path: "assets/items/travel-bag.png" },
  { key: "ending_bus_home", path: "assets/endings/bus-home.png" },
  { key: "ending_packing_room", path: "assets/endings/packing-room.png" },
  { key: "ending_packed_room", path: "assets/endings/packed-room.png" },
  { key: "ending_morning_room", path: "assets/endings/morning-room.png" },
  { key: "ending_yeongju_station", path: "assets/endings/yeongju-station.png" },
  { key: "ending_train_arrival", path: "assets/endings/train-arrival.png" },
  { key: "ending_seoul_station", path: "assets/endings/seoul-station.png" },
  { key: "ending_gyeongbokgung", path: "assets/endings/gyeongbokgung.png" },
  { key: "ending_amusement_park", path: "assets/endings/amusement-park.png" },
  { key: "ending_chapter1_final", path: "assets/endings/chapter1-ending-scene.png" },
  { key: "shop_sweatshirt", path: "assets/shop-icons/sweatshirt.png" },
  { key: "shop_cotton_pants", path: "assets/shop-icons/cotton-pants.png" },
  { key: "shop_shopping_bag", path: "assets/shop-icons/shopping-bag.png" },
  { key: "shop_shoe_box", path: "assets/shop-icons/shoe-box.png" },
  { key: "shop_shoe_box_front", path: "assets/shop-icons/shoe-box-front.png" },
  { key: "shop_shoe_box_side", path: "assets/shop-icons/shoe-box-side.png" },
  { key: "shop_paper_bag", path: "assets/shop-icons/paper-bag.png" },
  { key: "shop_jeans", path: "assets/shop-icons/jeans.png" },
  { key: "shop_denim_jacket", path: "assets/shop-icons/denim-jacket.png" },
  { key: "shop_check_shirt", path: "assets/shop-icons/check-shirt.png" },
  { key: "shop_jogger_pants", path: "assets/shop-icons/jogger-pants.png" },
  { key: "shop_padded_jacket", path: "assets/shop-icons/padded-jacket.png" },
  { key: "shop_hoodie_jacket", path: "assets/shop-icons/hoodie-jacket.png" },
  { key: "shop_white_tshirt", path: "assets/shop-icons/white-tshirt.png" },
  { key: "shop_running_shoes", path: "assets/shop-icons/running-shoes.png" },
  { key: "shop_sneakers", path: "assets/shop-icons/sneakers.png" },
  { key: "shop_canvas_shoes", path: "assets/shop-icons/canvas-shoes.png" },
  { key: "bacchus_item", path: "assets/ui/bacchus.png" },
  { key: "grass_tile", path: "assets/tiles/grass.png", fallback: "createGrassTileTexture" },
  { key: "path_tile", path: "assets/tiles/path.png", fallback: "createPathTileTexture" },
  { key: "sidewalk_tile", path: "assets/tiles/sidewalk.png", fallback: "createSidewalkTileTexture" },
  { key: "building_tile", path: "assets/tiles/building.png", fallback: "createBuildingTileTexture" },
  { key: "garden_tile", path: "assets/tiles/garden.png", fallback: "createGardenTileTexture" },
  { key: "road_tile", path: "assets/tiles/road.png", fallback: "createRoadTileTexture" },
  { key: "bench_tile", path: "assets/tiles/bench.png" },
  { key: "vehicle_stop_line", path: "assets/tiles/vehicle-stop-line.png" },
  { key: "samgakji_tiles", path: "assets/tilesets/samgakji-tiles.png" },
];

export const SPRITESHEET_ASSETS = [
  { key: "trash_slime", path: "assets/sprites/trash-slime.png", frameWidth: 128, frameHeight: 128 },
  { key: "trash_slime_2", path: "assets/sprites/trash-slime2.png", frameWidth: 128, frameHeight: 128 },
  { key: "trash_can", path: "assets/sprites/trash-can.png", frameWidth: 128, frameHeight: 128 },
  { key: "trash_can_2", path: "assets/sprites/trash-can2.png", frameWidth: 128, frameHeight: 128 },
  { key: "trash_can_3", path: "assets/sprites/trash-can3.png", frameWidth: 128, frameHeight: 128 },
  { key: "trash_plastic", path: "assets/sprites/plastic.png", frameWidth: 128, frameHeight: 128 },
  { key: "haenaem_sweep_down", path: "assets/sprites/haenaem-sweep-down.png", frameWidth: 90, frameHeight: 96 },
  { key: "haenaem_sweep_up", path: "assets/sprites/haenaem-sweep-up.png", frameWidth: 90, frameHeight: 96 },
  { key: "haenaem_sweep_left", path: "assets/sprites/haenaem-sweep-left.png", frameWidth: 90, frameHeight: 96 },
  { key: "haenaem_sweep_right", path: "assets/sprites/haenaem-sweep-right.png", frameWidth: 90, frameHeight: 96 },
  { key: "haenaem_walk_down", path: "assets/sprites/haenaem-walk-down-new.png", frameWidth: 64, frameHeight: 96 },
  { key: "haenaem_walk_up", path: "assets/sprites/haenaem-walk-up-new.png", frameWidth: 64, frameHeight: 96 },
  { key: "haenaem_walk_left", path: "assets/sprites/haenaem-walk-left-new.png", frameWidth: 64, frameHeight: 96 },
  { key: "haenaem_walk_right", path: "assets/sprites/haenaem-walk-right-new.png", frameWidth: 64, frameHeight: 96 },
  { key: "yeobi_walk_down", path: "assets/sprites/yeobi-walk-down.png", frameWidth: 64, frameHeight: 96 },
  { key: "yeobi_walk_up", path: "assets/sprites/yeobi-walk-up.png", frameWidth: 64, frameHeight: 96 },
  { key: "yeobi_walk_left", path: "assets/sprites/yeobi-walk-left.png", frameWidth: 64, frameHeight: 96 },
  { key: "yeobi_walk_right", path: "assets/sprites/yeobi-walk-right.png", frameWidth: 64, frameHeight: 96 },
  { key: "sunisuni_walk_down", path: "assets/sprites/sunisuni-walk-down.png", frameWidth: 64, frameHeight: 96 },
  { key: "sunisuni_walk_up", path: "assets/sprites/sunisuni-walk-up.png", frameWidth: 64, frameHeight: 96 },
  { key: "sunisuni_walk_left", path: "assets/sprites/sunisuni-walk-left.png", frameWidth: 64, frameHeight: 96 },
  { key: "sunisuni_walk_right", path: "assets/sprites/sunisuni-walk-right.png", frameWidth: 64, frameHeight: 96 },
  { key: "jjook_walk_down", path: "assets/sprites/jjook-walk-down.png", frameWidth: 64, frameHeight: 96 },
  { key: "jjook_walk_up", path: "assets/sprites/jjook-walk-up.png", frameWidth: 64, frameHeight: 96 },
  { key: "jjook_walk_left", path: "assets/sprites/jjook-walk-left.png", frameWidth: 64, frameHeight: 96 },
  { key: "jjook_walk_right", path: "assets/sprites/jjook-walk-right.png", frameWidth: 64, frameHeight: 96 },
  { key: "bus_right", path: "assets/vehicles/bus-right.png", frameWidth: 384, frameHeight: 192 },
  { key: "car_yellow_left", path: "assets/vehicles/car-yellow-left.png", frameWidth: 256, frameHeight: 128 },
  { key: "car_blue_left", path: "assets/vehicles/car-blue-left.png", frameWidth: 256, frameHeight: 128 },
  { key: "car_white_left", path: "assets/vehicles/car-white-left.png", frameWidth: 256, frameHeight: 128 },
  { key: "car_red_right", path: "assets/vehicles/car-red-right.png", frameWidth: 256, frameHeight: 128 },
  { key: "car_white_right", path: "assets/vehicles/car-white-right.png", frameWidth: 256, frameHeight: 128 },
  { key: "pedestrian_light", path: "assets/traffic/pedestrian-light.png", frameWidth: 64, frameHeight: 112 },
  { key: "sweat_effect", path: "assets/sprites/sweat-effect.png", frameWidth: 128, frameHeight: 128 },
  { key: "star_effect", path: "assets/sprites/star-effect.png", frameWidth: 128, frameHeight: 128 },
  { key: "heart_effect", path: "assets/sprites/heart-effect.png", frameWidth: 128, frameHeight: 128 },
  { key: "flowerbed_growth", path: "assets/sprites/flowerbed_growth.png", frameWidth: 160, frameHeight: 96 },
  { key: "flowerbed_growth2", path: "assets/sprites/flowerbed_growth2.png", frameWidth: 160, frameHeight: 96 },
  { key: "butterfly_idle", path: "assets/sprites/butterfly_idle.png", frameWidth: 64, frameHeight: 64 },
];

export const TILED_MAP = {
  key: "chapter1_map",
  jsonKey: "chapter1_map_json",
  path: "assets/maps/chapter1-samgakji-map.json",
};

export const AUDIO_ASSETS = [
  { key: "thanks_voice", path: "assets/audio/voice/thanks.mp3" },
  { key: "collect_cans_voice", path: "assets/audio/voice/collect-cans.mp3" },
  { key: "help_voice", path: "assets/audio/voice/i-will-help.mp3" },
  { key: "clear_slime_voice", path: "assets/audio/voice/clear-slime.mp3" },
  { key: "chapter1_bgm", path: "assets/audio/bgm/chapter1.mp3" },
  { key: "prologue_room_bgm", path: "assets/audio/bgm/prologue-room.wav" },
  { key: "prologue_summer_bgm", path: "assets/audio/bgm/prologue-summer.wav" },
  { key: "prologue_park_bgm", path: "assets/audio/bgm/prologue-park.wav" },
  { key: "chapter1_ending_bgm", path: "assets/audio/bgm/chapter1-ending.wav" },
  { key: "ambient_clothing_shop_bgm", path: "assets/audio/bgm/ambient-clothing-shop.wav" },
  { key: "ambient_hospital_bgm", path: "assets/audio/bgm/ambient-hospital.wav" },
  { key: "ambient_pharmacy_bgm", path: "assets/audio/bgm/ambient-pharmacy.wav" },
  { key: "ambient_bus_bgm", path: "assets/audio/bgm/ambient-bus.wav" },
  { key: "ambient_room_bgm", path: "assets/audio/bgm/ambient-room.wav" },
  { key: "ambient_train_bgm", path: "assets/audio/bgm/ambient-train.wav" },
  { key: "ambient_seoul_station_bgm", path: "assets/audio/bgm/ambient-seoul-station.wav" },
  { key: "ambient_gyeongbokgung_bgm", path: "assets/audio/bgm/ambient-gyeongbokgung.wav" },
  { key: "ambient_amusement_park_bgm", path: "assets/audio/bgm/ambient-amusement-park.wav" },
];

export const LAZY_IMAGE_KEYS = [
  "ending_bus_home",
  "ending_packing_room",
  "ending_packed_room",
  "ending_morning_room",
  "ending_yeongju_station",
  "ending_train_arrival",
  "ending_seoul_station",
  "ending_gyeongbokgung",
  "ending_amusement_park",
  "ending_chapter1_final",
  "hospital_interior",
  "pharmacy_interior",
  "clothing_store_interior",
];

export const LAZY_AUDIO_KEYS = [
  "chapter1_ending_bgm",
  "ambient_clothing_shop_bgm",
  "ambient_hospital_bgm",
  "ambient_pharmacy_bgm",
  "ambient_bus_bgm",
  "ambient_room_bgm",
  "ambient_train_bgm",
  "ambient_seoul_station_bgm",
  "ambient_gyeongbokgung_bgm",
  "ambient_amusement_park_bgm",
];
