export const GAME_CONFIG = {
  worldWidth: 1536,
  worldHeight: 960,
  playerSpeed: 135,
  waveSize: 30,
  totalGoal: 30,
  canCount: 20,
  yebiRemoveCount: 10,
  playerDisplaySize: 64,
  playerDisplayWidth: 64,
  playerDisplayHeight: 96,
  playerBodyWidth: 28,
  playerBodyHeight: 36,
  playerBodyOffsetX: 18,
  playerBodyOffsetY: 56,
  slimeDisplaySize: 42,
  broomItemDisplaySize: 44,
  yebiNpcDisplaySize: 72,
  baseSweepWidth: 112,
  baseSweepHeight: 84,
  upgradedSweepMultiplier: 2,
  sweepCooldownMs: 420,
  feedbackSparkleCount: 14,
  canFeedbackSparkleCount: 18,
  slimeSpawnMinDistance: 72,
  wideCameraZoom: 1.3,
  joystickRadius: 78,
  slimeRespawnDelayMs: 12000,
  maxSlimes: 25,
  rewardPerSlime: 100,
  recycleDepositReward: 100,
  recycleQuestUnlockMoney: 25000,
  jjookQuestUnlockMoney: 45000,
  drinkPrice: 1000,
  speedBuffMultiplier: 1.35,
  speedBuffDurationMs: 60000,
  jjookFollowDurationMs: 60000,
  sunisuniQuestUnlockMoney: 60000,
  sunisuniSpeedMultiplier: 0.55,
  sunisuniFollowDistance: 72,
  sunisuniMaxDistance: 220,
  sunisuniSpawn: { x: 1198, y: 690 },
  sunisuniBench: { x: 1202, y: 692 },
  sunisuniTree: { x: 1135, y: 646 },
  hospitalBuilding: { x: 152, y: 144 },
  pharmacyBuilding: { x: 353, y: 144 },
  hospitalDoor: { x: 152, y: 172 },
  pharmacyDoor: { x: 353, y: 172 },
  bacchusDurationMs: 60000,
  bacchusSweepMultiplier: 2,
  chapter1TargetMoney: 100000,
  recyclingCenter: { x: 1210, y: 420 },
  vendingMachine: { x: 690, y: 465 },
  jjookSpawn: { x: 685, y: 545 },
  walletSpawn: { x: 250, y: 735 },
  recycleBinHitboxWidth: 82,
  recycleBinHitboxHeight: 90,
};

export const DRINK_OPTIONS = [
  { key: "cider", label: "\uC0AC\uC774\uB2E4", texture: "drink_cider" },
  { key: "cola", label: "\uCF5C\uB77C", texture: "drink_cola" },
  { key: "water", label: "\uC0DD\uC218", texture: "drink_water" },
];

export const TILED_MAP_CONFIG = {
  key: "chapter1_map",
  chapter: 1,
  title: "\uCC55\uD130 1",
  mapName: "\uC0BC\uAC01\uC9C0 \uBCF5\uC9C0\uAD00",
  tilesetName: "samgakji_tiles",
  tilesetImageKey: "samgakji_tiles",
  visibleLayers: ["ground", "objects"],
  collisionLayer: "collision",
  objectLayer: "spawn",
  mapObjectsLayer: "map_objects",
};

export const PLAYER_TEXTURES = {
  down: "haenaem_walk_down",
  left: "haenaem_walk_left",
  right: "haenaem_walk_right",
  up: "haenaem_walk_up",
};

export const PLAYER_WALK_ANIMS = {
  down: "haenaem_walk_down_anim",
  left: "haenaem_walk_left_anim",
  right: "haenaem_walk_right_anim",
  up: "haenaem_walk_up_anim",
};

export const NPC_TEXTURES = {
  yeobi: {
    down: "yeobi_walk_down",
    left: "yeobi_walk_left",
    right: "yeobi_walk_right",
    up: "yeobi_walk_up",
  },
  sunisuni: {
    down: "sunisuni_walk_down",
    left: "sunisuni_walk_left",
    right: "sunisuni_walk_right",
    up: "sunisuni_walk_up",
  },
  jjook: {
    down: "jjook_walk_down",
    left: "jjook_walk_left",
    right: "jjook_walk_right",
    up: "jjook_walk_up",
  },
};

export const NPC_WALK_ANIMS = {
  yeobi: {
    down: "yeobi_walk_down_anim",
    left: "yeobi_walk_left_anim",
    right: "yeobi_walk_right_anim",
    up: "yeobi_walk_up_anim",
  },
  sunisuni: {
    down: "sunisuni_walk_down_anim",
    left: "sunisuni_walk_left_anim",
    right: "sunisuni_walk_right_anim",
    up: "sunisuni_walk_up_anim",
  },
  jjook: {
    down: "jjook_walk_down_anim",
    left: "jjook_walk_left_anim",
    right: "jjook_walk_right_anim",
    up: "jjook_walk_up_anim",
  },
};

export const TRASH_TEXTURES = {
  can: ["trash_can", "trash_can_2", "trash_can_3"],
  normal: ["trash_slime", "trash_slime_2"],
  plastic: ["trash_plastic"],
};

export const RECYCLE_BIN_CONFIG = [
  { type: "can", texture: "recycle_bin_can", xOffset: -84, yOffset: 28, label: "\uCEA0/\uACE0\uCCA0" },
  { type: "normal", texture: "recycle_bin_normal", xOffset: 0, yOffset: 28, label: "\uC885\uC774/\uC77C\uBC18" },
  { type: "plastic", texture: "recycle_bin_plastic", xOffset: 84, yOffset: 28, label: "\uD50C\uB77C\uC2A4\uD2F1" },
];

export const DIALOGUE_OVERLAY_TEXTURES = {
  jjookface: "jjook_default",
  jjook_lost: "jjook_lost",
  jjook_found: "jjook_found",
  jjook_smile: "jjook_smile",
  jjook_expectant: "jjook_expectant",
  jjook_playful: "jjook_playful",
  jjook_plogging: "jjook_plogging",
  jjook_default: "jjook_default",
  haenaem: "haenaem",
  haenaem_confused: "haenaem_confused",
  haenaem_touched: "haenaem_touched",
  haenaem_determined: "haenaem_determined",
  haenaem_surprised: "haenaem_surprised",
  haenaem_phone: "haenaem_phone",
  haenaem_sleepy_phone: "haenaem_sleepy_phone",
  haenaem_sweat: "haenaem_sweat",
  haenaem_dazed: "haenaem_dazed",
  mother_calm: "mother_calm",
  mother_smile: "mother_smile",
  mother_worried: "mother_worried",
  yeobi: "yeobi",
  hospital_staff: "hospital_staff",
  hospital_doctor: "hospital_doctor",
  chemist: "chemist",
  "sunisuni-portrait-sick": "sunisuni_portrait_sick",
  "sunisuni-portrait-smile": "sunisuni_portrait_smile",
  "sunisuni-portrait-worried": "sunisuni_portrait_worried",
  sunisuni_portrait_sick: "sunisuni_portrait_sick",
  sunisuni_portrait_smile: "sunisuni_portrait_smile",
  sunisuni_portrait_worried: "sunisuni_portrait_worried",
};

export const DIALOGUE_OVERLAY_PATHS = {
  jjook_default: "assets/portraits/jjook-default.png",
  jjook_lost: "assets/portraits/jjook-wallet-lost.png",
  jjook_found: "assets/portraits/jjook-wallet-found.png",
  jjook_smile: "assets/portraits/jjook-smile.png",
  jjook_expectant: "assets/portraits/jjook-expectant.png",
  jjook_playful: "assets/portraits/jjook-playful.png",
  jjook_plogging: "assets/portraits/jjook-plogging.png",
  haenaem: "assets/portraits/haenaem-default.png",
  haenaem_confused: "assets/portraits/haenaem-confused.png",
  haenaem_touched: "assets/portraits/haenaem-touched.png",
  haenaem_determined: "assets/portraits/haenaem-determined.png",
  haenaem_surprised: "assets/portraits/haenaem-surprised.png",
  haenaem_phone: "assets/portraits/haenaem-phone.png",
  haenaem_sleepy_phone: "assets/portraits/haenaem-sleepy-phone.png",
  haenaem_sweat: "assets/portraits/haenaem-sweat.png",
  haenaem_dazed: "assets/portraits/haenaem-dazed.png",
  mother_calm: "assets/portraits/mother-calm.png",
  mother_smile: "assets/portraits/mother-smile.png",
  mother_worried: "assets/portraits/mother-worried.png",
  yeobi: "assets/portraits/yeobi-default.png",
  hospital_staff: "assets/portraits/hospital-staff.png",
  hospital_doctor: "assets/portraits/hospital-doctor.png",
  chemist: "assets/portraits/pharmacist.png",
  sunisuni_portrait_sick: "assets/portraits/sunisuni-sick.png",
  sunisuni_portrait_smile: "assets/portraits/sunisuni-smile.png",
  sunisuni_portrait_worried: "assets/portraits/sunisuni-worried.png",
};
