import {
  ClothesQuestState,
  JjookQuestState,
  PackingQuestState,
  SunisuniQuestState,
} from "./QuestStates.js";

export function createInitialGameState() {
  return {
    totalCleanedCount: 0,
    totalRecycledCount: 0,
    shownSpecialOverlays: {},
    waveCleanedCount: 0,
    currentWave: 0,
    hasBroomUpgrade: false,
    hasDroppedBroomUpgrade: false,
    cleanedCanCount: 0,
    recyclingInventory: { normal: 0, can: 0, plastic: 0 },
    isRecycleMaster: false,
    inventoryCaptionQueue: [],
    isShowingInventoryCaption: false,
    jjookQuestState: JjookQuestState.LOCKED,
    hasAnnouncedJjookQuest: false,
    hasWallet: false,
    selectedDrink: null,
    drinkInventory: [],
    isSpeedBuffActive: false,
    isJjookFollowActive: false,
    isJjookClothesEscortActive: false,
    isJjookBusEscortActive: false,
    jjookFollowEndsAt: 0,
    jjookFollowTimer: null,
    jjookFollowCountdownEvent: null,
    shouldBuyJjookColaAfterFollow: false,
    jjookStateBeforeVending: null,
    shouldCompleteJjookAfterDrink: false,
    speedBuffTimer: null,
    speedBuffCountdownEvent: null,
    sunisuniQuestState: SunisuniQuestState.LOCKED,
    hasAnnouncedSunisuniQuest: false,
    hasPrescription: false,
    hasMedicine: false,
    hasBacchus: false,
    hospitalRevisitUsed: false,
    hasReceivedPharmacyDrink: false,
    isBacchusActive: false,
    bacchusTimer: null,
    bacchusCountdownEvent: null,
    clothesQuestState: ClothesQuestState.LOCKED,
    hasAnnouncedClothesQuest: false,
    travelPrepItems: [],
    packingQuestState: PackingQuestState.LOCKED,
    packingItems: [],
    isTravelPrepFanOpen: false,
    clothingShopModal: null,
    clothingShopSelectedKeys: new Set(),
    selectedClothingShopIndex: 0,
    clothingShopStepIndex: 0,
    clothingShopMode: "category",
    packingModal: null,
    packingSelectedKeys: new Set(),
    selectedPackingIndex: 0,
    packingStepIndex: 0,
    packingMode: "category",
    travelBus: null,
    permanentBusStopObjects: [],
    travelBusStopObjects: [],
    travelBusSequenceEvents: [],
    nextBusEscortWaitToastAt: 0,
    jjookIdleTween: null,
    jjookReturningHome: false,
    sunisuniReturningToBench: false,
    npcRoamState: {},
    nextNpcAmbientBubbleAt: 0,
    nextJjookAutoCleanAt: 0,
    interiorSceneGroup: null,
    questMarkers: {},
    vendingMenuOptions: [],
    selectedVendingIndex: 0,
    vendingMenuInputLockedUntil: 0,
    hasAnnouncedRecycleQuest: false,
    hasUnlockedYebi: false,
    hasUsedYebi: false,
    isMissionComplete: false,
    activeJoystickPointerId: null,
    joystickBase: { x: 0, y: 0 },
    mouseMoveTarget: null,
    isMouseMoveHeld: false,
    mouseMoveStartTime: 0,
    canSweep: true,
    thanksAudioBuffer: null,
    collectCansAudioBuffer: null,
    helpAudioBuffer: null,
    clearSlimeAudioBuffer: null,
    hasStartedAudioLoad: false,
    playerStart: { x: 170, y: 424 },
    broomSpawn: { x: 650, y: 420 },
    slimeSpawnPoints: [],
    finalFlowerPositions: null,
    mapPoints: {},
    mapObjects: {},
    objectWalls: null,
    objectCollisionRects: [],
    tutorialState: "intro",
    currentChapter: 1,
    isChapterComplete: false,
  };
}
